### ISSUE TITLE
DMCA attention

### ISSUE THREAD

**Issue by laosb** [XCRailway/XCRailMinecraftBatchhAder#4]
Dear XCRailway,

[Your file `UnRAR.exe` in your repo](https://github.com/XCRailway/XCRailMinecraftBatchhAder/blob/master/assents/mccore/UnRAR.exe) is a copyrighted freeware. You should put it's copyright notice in the LICENSE file.

What' more, you're using CC0 for this repo but still says that you have the copyright of these things. It's a conflict and please change this behavior.

**Comment by XCRailway** [comment]
OK

**Comment by XCRailway** [comment]
Done

**Comment by laosb** [comment]
Actually you didn't solve the License problem. You should either delete your copyright notice, or remove CC0 license.

**Comment by XCRailway** [comment]
OK

**Comment by laosb** [comment]
Another attention: Without unrar.exe this program won't start.

**Comment by XCRailway** [comment]
。。。

**Comment by XCRailway** [comment]
Done

**Comment by XCRailway** [comment]
You can download it. It can start.
